---
title: "Selected Talks"
editor: visual
---

2022, Assessing the economic performance of a government characterised by populist rhetoric in Hungary: A synthetic control approach, ECPR General Conference

2021, Macroeconomics and Politics in Hungary: How an Illiberal Government Characterised by Populist Rhetoric Deals With its Public Budget, The Doctoral Student Association of the University of Pécs Conference (PTE DOK)

2021, Macroeconomics, Policies, and CEE: a Machine Learning Approach to Social Investment and Social Protection Policies, inGRID Workshop

2020, A Review of Quasi-Experimental and Predictive Methodologies in Relation to Measuring Populism and its Outcomes, ASEEES 52nd Annual Convention

2020, FATIGUE Project Workshop, Science is Wonderful! European Commission Outreach Event, 2019

Economic populism, fiscal policies and budget deficits: the sustainability implications for Central and Eastern Europe, WINIR Symposium 2019

2019, Present and future populist policies in Europe: the Cases of Hungary and Bulgaria, RSA Winter Conference

2019, The New Populist Policies Prescriptions, UACES 49th Annual Conference